//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management_System_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssueBook
    {
        public int issueCode { get; set; }
        public int MemberCode { get; set; }
        public int BookCode { get; set; }
        public System.DateTime IssueDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> ActualReturnDate { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Member Member { get; set; }
    }
}
