--select * from Products
--select * from Categories
--select * from CustomerCustomerDemo
--select * from CustomerDemographics
--select * from Customers
--select * from Employees
--select * from EmployeeTerritories
--select * from Orders
--select * from [order details]



--------------------Assignment -1   Northwind Queries-------

--Table: Customers
select * from Customers
--1. Display the “Company Name” and “Contact Name” from Customers table
SELECT [COMPANYNAME], [CONTACTNAME] FROM Customers
--2. Find the Customers who are staying wither in USA, UK, Germany, France
SELECT * FROM CUSTOMERS WHERE COUNTRY IN ('USA', 'UK', 'GERMANY', 'FRANCE')

--3. Find the Customers whose “Company Name” starts with G
SELECT * FROM CUSTOMERS WHERE COMPANYNAME LIKE 'G%'

--4. List all the Customers who are located in Paris
SELECT * FROM CUSTOMERS WHERE CITY ='PARIS'

--5. List the Customer details whose postal code start with 4
SELECT * FROM CUSTOMERS WHERE POSTALCODE LIKE '4%'

--6. List all the Customers who neither stay in Canada nor in Brazil
SELECT * FROM CUSTOMERS WHERE COUNTRY NOT IN ('CANADA', 'BRAZIL')

--7. Print total number of Customers for each country.
SELECT COUNT(CUSTOMERID) AS [TOTAL NUMBER OF CUSTOMER] FROM CUSTOMERS GROUP BY Country

--8. List Customers detail based on Country and City
SELECT * FROM CUSTOMERS ORDER BY COUNTRY, CITY

--9. List all the manager from the Customers table
SELECT * FROM CUSTOMERS WHERE CUSTOMERID IN (SELECT CUSTOMERID FROM EMPLOYEES )

--10. List all Customers details where “company name” contains aphostophy (‘)
SELECT * FROM  CUSTOMERS WHERE COMPANYNAME LIKE '%''%'




--------------------Table: Products----------
SELECT * FROM Products

--11. List all the products for CategoryID 4 and UnitsInStock is more then 50
SELECT * FROM PRODUCTS WHERE CATEGORYID=4 AND UnitsInStock>50

--12. List ProductName, UnitPrice, UnitsInStock, NetStock (i.e. UnitPrice * UnitsInStock)
SELECT PRODUCTNAME, UNITPRICE, UNITSINSTOCK, (UNITPRICE * UNITSINSTOCK) AS NETSTOCK FROM Products

--13. List Maximum and Minimum UnitPrice
SELECT MAX(UNITPRICE), MIN(UNITPRICE) FROM Products

--14. Count the number of products whose UnitPrice is more then 50
SELECT COUNT(PRODUCTID) AS [NUMBER OF PRODUCTS] FROM PRODUCTS WHERE UNITPRICE >50

--15. List product count base on CategoryID. List the data where count is more then 10
SELECT CATEGORYID, COUNT(PRODUCTID) AS [PRODUCT COUNT BASED ON CATEGORY ID] FROM PRODUCTS   GROUP BY CATEGORYID 

SELECT 
CASE
	WHEN COUNT(PRODUCTID)>10 THEN COUNT(PRODUCTID) 
END AS [PRODUCT COUNT], CATEGORYID
FROM PRODUCTS GROUP BY CATEGORYID
--16. Find all the products where UnitsInStock iS less than Reorder Level
SELECT * FROM PRODUCTS WHERE UnitsInStock < ReorderLevel

--17. List Category wise, Supplier wise product count
SELECT COUNT(PRODUCTID) AS PRODUCTCOUNT, SUPPLIERID, CATEGORYID FROM Products GROUP BY SupplierID, CategoryID ORDER BY SUPPLIERID, CategoryID

--18. All Products whose UnitsInStock is less than 5 units are entitles for placing order by 50 units for 
--others place the order by 30 units. Display ProductID, ProductName, UnitsInStock,
SELECT PRODUCTID, PRODUCTNAME,
CASE
	WHEN UNITSINSTOCK<5 THEN UNITSINSTOCK+50
	ELSE UNITSINSTOCK + 30
END AS [UNITS IN STOCK] FROM Products

SELECT * FROM Products


 
----------------OrderedUnits-------

--19. List 3 costliest product
SELECT TOP 3 * FROM PRODUCTS ORDER BY UnitPrice DESC

--20. List all the products whose CategoryID is 1 and SupplierID is either 10 or 12 or CategoryID is 4 
--and SupplierID is either 14 or 15.
SELECT  * FROM PRODUCTS WHERE (CategoryID=1 AND SupplierID IN (10,12)) OR (CategoryID=4 AND SupplierID IN (14, 15))



---------Table: Orders--------

SELECT * FROM Orders
--21. List all the orders placed in month of February
SELECT * FROM ORDERS WHERE DATEPART(MM, ORDERDATE)=2

--22. List year wise order count
SELECT COUNT(ORDERID) AS [YEAR WISE ORDER COUNT], DATEPART(YYYY, ORDERDATE) FROM ORDERS GROUP BY DATEPART(YYYY, OrderDate)

--23. List the ShipCountry for which total order placed is more than 100
--Example
--ShipCountry OrderCount
--USA 122
SELECT SHIPCOUNTRY, COUNT(ORDERID) FROM ORDERS GROUP BY ShipCountry HAVING COUNT(ORDERID)>100 

--24. List the data as per the order month (Jan – Dec)
SELECT * FROM ORDERS ORDER BY DATEPART(MM, ORDERDATE)

--25. List unique country name in ascending order where product is shipped
SELECT DISTINCT(SHIPCOUNTRY) FROM ORDERS ORDER BY ShipCountry

--26. List CustomerID, ShipCity, ShipCountry, ShipRegion from Ordrs table. If ShipRegion is null then 
--display message as “No Region”27. 
SELECT CUSTOMERID, SHIPCITY, SHIPCOUNTRY, 
CASE
	WHEN SHIPREGION IS NULL THEN 'No Region'
	ELSE SHIPREGION
END AS [SHIP REGION] FROM ORDERS  

--List the detail of first order placed
SELECT TOP 1 * FROM ORDERS

SELECT * FROM ORDERS WHERE ORDERDATE IN (SELECT MIN(ORDERDATE) FROM ORDERS)


--28. List Customer wise, Year wise (Order date) order placed
--Example
--CustomerID Year OrderCount
-- ANATR 1996 1
--BONAP 1997 8
SELECT CUSTOMERID, DATEPART(YYYY, ORDERDATE) AS YEAR, COUNT(ORDERID) AS [ORDER COUNT] FROM ORDERS GROUP BY CustomerID


--29. List all the orders handled by employeeid 4 for the month of December
SELECT * FROM ORDERS WHERE EmployeeID=4 AND DATEPART(MM, ORDERDATE) =12


--30. List employee wise , year wise, month wise ordercount
SELECT EMPLOYEEID, DATEPART(YYYY, OrderDate), DATEPART(MM, ORDERDATE), COUNT(ORDERID) FROM ORDERS GROUP BY EmployeeID


------Table: [Order Details]

--31. List all the data of [Order Details] table

--32. List ProductID, UnitPrice, Qty and Total. Sort data on Total column with highest value on top

--33. In above query, 
--If Total is more than 10000 display 10% discount on Total cost
--If Total is more than 5000 display 5% discount on Total cost
--If Total is more than 3000 display 2% discount on Total cost
--else Rs. 300 as discount if total is more than 1000
--No discount for Total less than 1000


--34. List Total order placed for each OrderId


--35. List minimum cost and maximum cost order value



-------------------JOIN AND SUBQUERY ASSIGNMENT------------------------


--1 LIST ALL THE PRODUCTS DETAILS WHOSE CATEGORY IS SAME AS 'TOFU'


--2 LIST ALL THE PRODUCTS DETAILS FOR THE CATEGORY 'BEVERAGES'


--3 LIST ALL THE ORDERS PLACED BY THE COMPANY NAME "ISLAND TRADING"


--4 LIST COMPANY NAME AND NO OF ORDER COUNT PLACED BY EACH COMPANY


--5 LIST ORDERID, CUSTOMER_COMAPNAYNAME FOR ALL THE ORDERS WHICH ARE HANDLE BY THE EMPLOYEES WHOSE TITLE IS "SALES MANAGER"




--6 LIST 3RD HIGHEST COSTLIEST PRODUCT


--7 FOR THE PRODUCT TABLE DISPLAY PRODUCTNAME AND CATEGORYNAME. ARRANGE AS PER THE CATEGORYNAME


--8 FOR THE ORDERS TABLE DISPLAY ORDERID CUSTOMER_COMPANYNAME AND EMPLOYEE_FULLNAME


--9 LIST ORDERID, EMPLOYEE_FULLNAME, CUSTOMER_COMPANYNAME, CATEGORYNAME, SUPPLIER_COMPANYNAME, PRODUCTNAME, ORDERDETAIS_UNIRPRICE, ORDERDETAILS_QUANTITY , NETSTOCK


--10 LIST ALL THE ORDERS (ORDERID, PRODUCTNAME) PLACED BY THE CUSTOMER IN LONDON


--11 FOR THE COSTLIEST PRODUCT DISPLAY PRODUCTNAME, UNITPRICE, CATEGORYNAME, SUPPLIER_CONTACTNAME--12 LIST ALL THE PRODUCTNAME WHOSE ORDER PLACED IN MONTH OF AUGUST


--13 LIST ORDERID, QUANTITY FOR ALL THE ORDERS. ASSIGNED RANK AS PER THE HIGHEST OT LOWEST QUANTITY. DO NOT MISS ANY NUMBER
-- WHILE ASSIGNING THE RANK


--14 List all the products for the category “Dairy Product”


--15 List all the products which is supplied by the company “Bigfoot Breweries” for the category “Beverages”


--16 Print CategoryName , Supplier Comapny name and product count for each category and supplier
--17 PRINT REGION AND TERRITORYDESCRIPTION NAME IN ASCENDING ORDER


--18 PRINT EMPLOYEES NAME, REGION NAME, CITY AND COUNTRY --(check for the error, no region relationship)


--19 FOR EACH CATEGORIES PRINT CATEGORYNAME AND SUPPLIERS NAME


--20 PRINT EMPLOYEE TITLEOFCOURTESY, EMPLOYEE FIRST + LASTNAME , EMPLOYEE TITLE, MANAGER TITLEOFCURTASY, 
--MANAGER FIRSTNAME + LASTNAME, MANAGER TITL




------------NORTHWIND DATABASE – PROGRAMMING ASSIGNMENT----------


--1. WRITE A PROCEDURE WHICH TAKES CATEGORY NAME AS A PARAMETER AND RETURN 
--ALL PRODUCTS WHICH MATCH WITH THE CATEGORY NAME. IF NAME NOT EXIST PRINT 
--MESSAGE



--2. TAKE COUNTRY NAME AS THE PARAMETER AND RETURN ALL CUSTOMERS FROM THAT 
--COUNTRY


--3. WRITE INSERT, UPDATE AND DELETE PROCEDURE FOR EMPLOYEES TABLE. IF ANY 
--STATEMENT FAIL RAISE PROPER ERROR MESSAGE
--PARAMETER : 
--EMPLOYEEID LASTNAME FIRSTNAME TITLE TITLEOFCOURTESY BIRTHDATE HIREDATE ADDRESS CITY REGION POSTALCODE COUNTRY


--4. TAKE REGIONDESCRIPTION AS A PARAMETER
--PRINT REGIONDESCRIPTION, TERRITORY DESCRIPTION, AND EMPNAME


--5. PRODUCTS TABLE
--WRITE A PROCEDURE WHICH CHECKS UNITSINSTOCK AND UNITSONORDER
--DISPLAY ALL PRODUCTS DETAILS (PRODUCTNAME, UNITPRICE, UNITSINSTOCK, 
--UNITSONORDER, DIFFERENCE ) where UNITSONORDER is more then UNITSINSTOCK


--6. ORDER DETAILS TABLE
--TAKE ORDERID AS PARAMETER
--FOR THE ORDERID PRINT PRODUCTNAME, UNITPRICE, QUANTITY, DISCOUNT, TOTAL I.E 
--UNITPRICE * QUNATITY, DISCOUNTAMOUNT, FINAL PRICE I.E. TOTAL –DISCOUNT AMOUNT
--7. WRITE A PROCEDURE WHICH INSERT IN PRODUCTTABLE
--PARAMETER FOR PROCEDURE PRODUCTNAME, UNITPRICE AND CATEGORYNAME
--CHECK IF CATEGORYNAME EXIST THEN ADD PRODUCTS WITH EXISTING CATEGORYID
--IF CATEGORYNAME DOES NOT EXIST FIRST INSERT IN CATEGORY TABLE
--READ CATEGORYID WHICH IS IDENTITY FIELD
--AND INSERT NEW INSERTED ID IN PRODUCT TABLE AS CATEGORYID



--8. ORDERS TABLE
--TAKE YEAR AS PARAMETER TO PROCEDURE
--PRINT IN EACH QUARTER HOW MANY ORDERS BOOKED,
--EXAMPLE IN Q-1 100
 
 
 
 --Q-2 150 ….
--IF YEAR NOT EXIST PRINT ERROR MESSAGE


--9. TABLE ORDERS AND ORDER DETAILS –OUT PARAMETER
--TAKE YEAR AND MONTH AS PARAMETER AND RETURN
--TOTAL REVENUE GENERATED SUM(UNITPRICE * QTY – DISCOUNT)


--10. FOR EACH EMPLOYEE PRINT EMPLOYEE FULL NAME, BIRTHDATE, HIREDATE, AGE (IN 
--YEARS) AT THE TIME OF HIRING, RETIREMENT DATE. (60 YEARS)FUNCTIONS
--1. TAKE PRODUCTNAME AS PARAMETER AND RETURN UNITPRICE
--2. TAKE PRODUCTNAME AS PARAMETER AND RETURN UNITSINSTOCK AND 
--UNINTSONORDER



--3. TAKE POSTALCODE AS PARAMETER AND RETURN CUSTOMER NAME. IF POSTAL CODE IS 
--NOT VALID DISPLAY ERROR MESSAGE



--4. TAKE COUNTRY AS PARAMETER AND RETURN CITY AND POSTALCODE FOR A CUSTOMERS

--5. TAKE EMPLOYEE FIRSTNAME AND LASTNAME AS PARAMETER AND RETURN ALL 
--CUSTOMERS COMPANY NAME, CONTACTNAME, CONTACTTILE



--6. TAKE YEAR AND EMPLOYEENAME AND DISPLAY AMOUNT OF ORDERS HANDLE BY THE 
--EMPLOYEE IN A YEAR (SUM OF QUANTITY)



--7. TAKE YEAR AND MONTH AS PARAMETER AND RETURN NO OF ORDERS SHIPPED IN THE 
--GIVEN MONTH



--8. TAKE PRODUCTNAME AS PARAMTER AND RETURN TOTLA UNITS OF ORDER PLACED FOR 
--THE PRODUCT (SUM(ORDERED QUANTITY)
--Hint: use Products and [Order Details] table



--9. TAKE ORDERID AS PARAMETER AND RETURN TOTAL UNITS OF ORDER PLACE FOR THE 
--ORDERI