--1	LIST ALL EMPS WHO ARE WORKING IN DEPT 20 AND EARNING MORE THEN 2500


--2	LIST ALL EMPS WHOSE JOB IS EITHER MANAGER OR CLERK OR ANALYST


--3	LIST ALL EMPS WHO ARE WORKING AS CLERK IN DPET 10 OR MANAGER FORM DEPT 30

--4	LIST ALL EMPS WHOSE SALARY IN RANGE OF 3000 TO 5000


--5	Find the employees whose commission is greater than 50 percent of his salary. 


--6	LIST ALL EMPS WHOSE COMM IS NOT NULL (means who are earning commission)
