// <auto-generated />
namespace EF_Code_First_Demo1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _01_createdb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_01_createdb));
        
        string IMigrationMetadata.Id
        {
            get { return "202107060240404_01_createdb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
